Upload photos
ti-broish/results pull request #72
Opened 2023-03-01 22:43 UTC by konstantinabl

- Adds new component for multi image upload
- Adds component to violation form
- Allows sending of violation with images

2023-03-03 07:35 UTC, hkdobrev requested changes

2023-03-03 07:35 UTC, hkdobrev commented on src/components/ViolationForm.js
> +          .catch((error) => console.log(error))
При грешка от сървъра трябва тази грешка да се обработва, а в момента се игнорира.

2023-03-03 07:35 UTC, hkdobrev commented on src/components/ViolationForm.js
> +  const saveImages = async (images) => {
тези няколко функции трябва да са преизползваеми когато снимките се качват от друго място

2023-03-03 07:35 UTC, hkdobrev commented on src/components/ViolationForm.js
> +        console.log('Снимката беше запазена')
Може ли да махнем console.log съобщенията? Вместо това трябва да показваме грешки от сървъра. Например имаме ограничение до 50МБ на body size (тоест това е в base64 формат, а не оригиналната снимка).
Добре и самият браузър да проверява за това преди да го прати и да показва съобщение.
А ако сървърът върне грешка да се покаже.

2023-03-03 17:07 UTC, vladiangelov commented on src/utils/uploadPhotosHelper.js
> +  return convertedImages
Мисля, че можеш да го рефакторираш по този начин:

```suggestion
  return await Promise.all(
    images.map(async (image) => {
      return await convertToBase64(image)
    })
  )
```

2023-03-04 18:37 UTC, vladiangelov commented on src/components/UploadPhotos.js
> +      <label class="label">
```suggestion
      <label className="label">
```

2023-03-04 19:24 UTC, vladiangelov commented on src/components/ViolationForm.js
>  const CommentFormStyle = styled.form`
Знам, че не е част от твоята работа, но ако може да вмъкнеш този edit на CSS-a, за да е по-добре подравнена формата. Освен това е хубаво да я погледнем на mobile, защото е доста малка.

```suggestion
const CommentFormStyle = styled.form`
  width: 100%;

  .errorMsg {
    color: red;
  }

  textarea {
    width: 80%;
    height: 50px;
    padding: 20px;
    margin-left: 5px;
    margin-bottom: 10px;
  }

  input[type='radio'] {
    margin: 5px;
    vertical-align: middle;
  }

  .inputLabel {
    display: block;
    margin-top: 10px;
    margin-left: 5px;
    padding: 5px;
  }

  input[type='text'] {
    width: 80%;
    font-size: 18px;
    padding: 10px;
    border: 1px solid #eee;
    margin-bottom: 10px;
    box-sizing: border-box;
    margin-left: 5px;
  }

  select {
    margin-left: 5px;
    padding: 5px;
  }

  .successfulMessage {
    color: green;
  }

  .unsuccessfulMessage {
    color: red;
  }

  button {
    padding: 10px;
    margin: 20px 5px;
  }
`
```

2023-03-06 21:18 UTC, hkdobrev commented on src/components/UploadPhotos.js
> +    top: -1000px;
С този custom стил на `<input type="file">` се скрива информацията дали и колко файла са избрани. Мисля, че може би трябва да използваме plugin, което да оправи UX-а на качването така че да може да се показват снимките, да може да се цъка много пъти и да добавя снимки и да има преглед в браузъра преди качването, за да е сигурен човек, че е снимал всичко.

На този етап, нека го пуснем така, но имаме доста да подобряваме UX-a, за да е устойчив интерфейса на всякакви ползвания и да няма оплаквания в изборния ден.

2023-03-06 21:18 UTC, hkdobrev approved these changes

2023-03-06 22:12 UTC, konstantinabl commented on src/components/UploadPhotos.js
> +    top: -1000px;
Съгласна съм и аз забелязах това за броя на файлове.Ще го подобрим

2023-03-06 22:12 UTC, merged