Fix validation violation form
ti-broish/results pull request #82
Opened 2023-03-12 16:34 UTC by konstantinabl

- Adds yup validation to the form

2023-03-13 22:47 UTC, hkdobrev requested changes

2023-03-13 22:47 UTC, hkdobrev commented on src/components/sectionSelector/DropDown.js
> +      <p style={{ color: 'red' }}>{errors?.message}</p>
```suggestion
      {errors && <p style={{ color: 'red' }}>{errors.message}</p>}
```
така няма да имаме излишни параграфи, които могат да влияят на пространството.

2023-03-13 22:47 UTC, hkdobrev commented on src/components/sectionSelector/DropDown.js
>      {label && <label className="inputLabel">{label}</label>}
```suggestion
    {label && <label className="inputLabel">
    	{label}
	    {required && <span style={{ color: 'red' }}>"*"</span>}
    </label>}
```
Нека сложим звездичка до задължителните полета.

2023-03-13 22:47 UTC, hkdobrev commented on src/components/ViolationForm.js
> +          <p className="errorMsg">{errors.description?.message}</p>
```suggestion
					{errors.description &&
          	<p className="errorMsg">{errors.description.message}</p>}
```
Нека променим и другите съобщения така, че да не добавяме празни параграфи, когато няма грешки.

2023-03-13 22:47 UTC, hkdobrev commented on src/components/ViolationForm.js
> +    section: yup.string(),
Липсва валидация за `country`. Не съм сигурен дали ще може да я направим conditional на база на `isAbroad` полето.

2023-03-14 20:29 UTC, konstantinabl commented on src/components/ViolationForm.js
> +    section: yup.string(),
@hkdobrev нправих я къндишънъл, но не работи и не знам защо
Нямам много време да погледна днес

2023-03-17 00:47 UTC, hkdobrev approved these changes

2023-03-17 00:48 UTC, merged