Добавяне на recaptcha при изпращане на сигнал
ti-broish/results pull request #84
Opened 2023-03-13 17:29 UTC by dgeorgiev

Това е имплементацията за #47 
При верификация се добавя header x-recaptcha-token към `post` заявката.

2023-03-13 23:12 UTC, hkdobrev requested changes

2023-03-13 23:12 UTC, hkdobrev commented on src/components/ProtocolForm.js
> +        <GoogleReCaptcha onVerify={handleVerify} />
Виждал съм проблеми с Google Recaptcha, когато формата страницата стои заредена повече от 60 секунди и тогава се submit-не, Google Recaptcha бакенда отказва token-а, тъй като е expired и вече не е актуален за проверката.

Плъгинът, който ползваме тук има решение за това с помощта `setRefreshReCaptcha`.

Но всъщност, още по-добре и препоръчителния подход, който и от плъгина предлагат е да използваме [`useGoogleReCaptcha`](https://github.com/t49tran/react-google-recaptcha-v3#react-hook-usegooglerecaptcha-recommended-approach).

С това ще е доста по-лесно да `useGoogleReCaptcha` и `useCallback`, за да генерираме `token` в момента на изпращане на формата.

Спрямо техния пример, няма нужда да използваме `useEffect`, защото може само когато се изпраща формата да генерираме `token`.

2023-03-13 23:12 UTC, hkdobrev commented on src/components/App.js
> +      reCaptchaKey="6LfqhYUkAAAAAAp-KRpwLPTROD1jrAQlQQV_L8R8"
```suggestion
      reCaptchaKey="process.env.GOOGLE_RECAPTCHA_KEY"
```

Нека преместим този ключ в `.env`?
`.env` файлът се използва само за development и се използват други стойности при deployment, които ще ги наглася допълнително.

2023-03-14 05:22 UTC, dgeorgiev commented on src/components/ProtocolForm.js
> +        <GoogleReCaptcha onVerify={handleVerify} />
Пропуснал съм, добра идея ще я обновя имплементацията на hook.

2023-03-14 05:22 UTC, dgeorgiev commented on src/components/App.js
> +      reCaptchaKey="6LfqhYUkAAAAAAp-KRpwLPTROD1jrAQlQQV_L8R8"
Ще го изместя, благодаря.

2023-03-15 12:55 UTC, dgeorgiev commented
@hkdobrev готово - обнових имплементацията, погледни когато можеш 🙇

2023-03-15 13:33 UTC, hkdobrev approved these changes

2023-03-15 13:47 UTC, merged